FROM adoptopenjdk/openjdk11:alpine-jre
LABEL maintainer="svsrvardhan@gmail.com"
COPY /target/devops-docker.jar /home/saripalli/git/github-from-eclipse/raghu/devops-docker.jar
CMD ["java","-jar","/home/devops-docker.jar"]